# -*- coding: utf-8 -*-
# Individuelle Inhalte für die 27 Produkt-Detailseiten (Kurzcheck-Format).
# verdict = 1-2 Sätze Kurzurteil | desc = 2 Absätze | pros/cons ehrlich | faqs 2-3

CONTENT = {
"shanwan-bt-white": dict(
  verdict="Solider Budget-Einstieg: Für rund 40 € bekommst du einen Bluetooth-Teleskop-Controller mit fast tausend Amazon-Bewertungen bei 4,1 Sternen — für Gelegenheitsspieler völlig ausreichend.",
  desc=["Der weiße ShanWan Bluetooth-Controller gehört zu den meistgekauften Budget-Modellen auf Amazon.de. Das Teleskop-Design spannt dein Handy zwischen die beiden Griffhälften, die verstellbare Joystick-Höhe ist in dieser Preisklasse eine Seltenheit. Über die Key-Mapping-Funktion lassen sich auch Spiele ohne native Controller-Unterstützung mit Tasten belegen.",
   "Klar ist aber auch: Bluetooth bedeutet spürbar mehr Input-Lag als USB-C-Modelle wie der GameSir X5 Lite. Für kompetitive Shooter ist das nichts — für Cloud Gaming, RPGs und entspannte Sessions auf der Couch reicht es locker."],
  pros=["Verstellbare Joystick-Höhe — selten unter 50 €","Key-Mapping für Spiele ohne Controller-Support","4,1 Sterne bei 977 Bewertungen — bewährtes Modell","Funktioniert mit Android und iOS"],
  cons=["Bluetooth-Latenz — nicht ideal für kompetitive Shooter","Verarbeitung spürbar einfacher als bei GameSir & Co."],
  faqs=[("Funktioniert der ShanWan Controller mit dem iPhone?","Ja, per Bluetooth koppelt er sich mit iOS und Android. Beachte aber: Nicht jedes iOS-Spiel unterstützt Key-Mapping — native Controller-Unterstützung ist auf dem iPhone die zuverlässigere Option."),
        ("Ist Bluetooth für Gaming schnell genug?","Für Casual Games, RPGs und Cloud Gaming ja. Bei schnellen Shootern merkst du die Latenz — dort sind USB-C-Controller wie der GameSir X5 Lite die bessere Wahl.")]),
"trust-gxt-rgb": dict(
  verdict="Der Trust GXT 735G Mylox bietet echte Analogsticks, Dual-Vibration und bis zu 12 Stunden Akku — ein ordentliches Gesamtpaket für rund 40 €, mit RGB als Bonus.",
  desc=["Trust ist als europäische Zubehör-Marke ein bekannter Name — der GXT 735G Mylox ist ihr Teleskop-Controller fürs Smartphone. Er setzt auf echte Analogsticks statt Folientasten, Dual-Vibration fürs Spielgefühl und eine RGB-Beleuchtung, die sich bei Bedarf abschalten lässt. Mit bis zu 12 Stunden Akkulaufzeit hält er länger durch als viele Konkurrenten.",
   "Die Verbindung läuft über Bluetooth 5.0 — stabil, aber wie bei allen Bluetooth-Controllern mit etwas mehr Latenz als bei USB-C-Modellen. Wer eine europäische Marke mit erreichbarem Support bevorzugt, bekommt hier eine sichere Alternative zu den China-Direktimporten."],
  pros=["Bis zu 12 Stunden Akkulaufzeit","Dual-Vibration — spürbares Feedback","Europäische Marke mit erreichbarem Support","RGB abschaltbar"],
  cons=["Bluetooth-Latenz höher als bei USB-C-Controllern","Kein Hall-Effect — Stick-Drift langfristig möglich"],
  faqs=[("Hat der Trust GXT 735G Hall-Effect-Sticks?","Nein, er nutzt klassische Potentiometer-Sticks. Bei intensiver Nutzung kann langfristig Stick-Drift auftreten. Driftfreie Alternativen in der Preisklasse: 8BitDo Ultimate Mobile oder GameSir X5 Lite."),
        ("Passt mein Handy in den Teleskop-Rahmen?","Der Rahmen dehnt sich für gängige Smartphone-Größen. Sehr dicke Hüllen solltest du vor dem Einspannen abnehmen.")]),
"shanwan-teleskop-black": dict(
  verdict="Der schwarze ShanWan-Teleskop-Controller ist mit rund 34 € eines der günstigsten Modelle im Sortiment — 4,2 Sterne bei 768 Bewertungen zeigen: Für den Preis macht er wenig falsch.",
  desc=["Wie sein weißes Schwestermodell setzt der schwarze ShanWan auf ein Teleskop-Design mit verstellbarer Joystick-Höhe und linearem Auslöser. Das Handy wird zwischen die Griffe gespannt, gekoppelt wird per Bluetooth — ohne App-Zwang, ohne Abo.",
   "Für 34 € ist das ein fairer Deal für alle, die Controller-Gaming erst einmal ausprobieren wollen, bevor sie 80 € für einen GameSir G8 ausgeben. Erwarte keine Premium-Haptik: Die Tasten sind funktional, aber nicht auf dem Niveau der Markengeräte."],
  pros=["Einer der günstigsten Teleskop-Controller (ca. 34 €)","4,2 Sterne bei 768 Bewertungen","Verstellbare Joystick-Höhe","Kein App-Zwang"],
  cons=["Einfache Tastenhaptik","Bluetooth-Latenz — für schnelle Shooter ungeeignet"],
  faqs=[("Was ist der Unterschied zum weißen ShanWan-Modell?","Technisch sind beide sehr ähnlich (Bluetooth, Teleskop, verstellbare Sticks). Der schwarze ist meist ein paar Euro günstiger — nimm einfach die Farbe/den Preis, der dir besser passt."),
        ("Lohnt sich der Aufpreis zu einem GameSir?","Wenn du regelmäßig spielst: ja. USB-C-Modelle wie der GameSir X5 Lite (ca. 38 €) haben praktisch keinen Input-Lag. Für Gelegenheitsspieler reicht der ShanWan.")]),
"easysmx-m15": dict(
  verdict="Der EasySMX M15 kombiniert mechanische Tasten mit Hall-Effect-Sticks und -Triggern — ein technisch starkes Paket im auffälligen Mecha-Design für rund 50 €.",
  desc=["Der M15 ist EasySMX' Angriff auf die Mittelklasse: Mechanische Tasten mit knackigem Feedback, dazu Hall-Effect-Sticks und -Trigger, die per Magnetsensor arbeiten und damit dauerhaft driftfrei bleiben. Diese Kombination findest du sonst erst in deutlich teureren Controllern.",
   "Das kantige Mecha-Design ist Geschmackssache — auffällig ist es allemal. Verbunden wird wahlweise per Bluetooth oder USB-C-Kabel; für latenzkritische Spiele empfehlen wir die Kabelverbindung. Mit 4,2 Sternen bei über 700 Bewertungen hat sich der M15 eine solide Fanbasis erspielt."],
  pros=["Hall-Effect-Sticks UND -Trigger — dauerhaft driftfrei","Mechanische Tasten mit präzisem Druckpunkt","Wahlweise Bluetooth oder USB-C","4,2 Sterne bei 721 Bewertungen"],
  cons=["Mecha-Optik polarisiert","Etwas größer/schwerer als klassische Teleskop-Controller"],
  faqs=[("Was bringen Hall-Effect-Trigger?","Sie messen den Tastendruck magnetisch statt über mechanische Kontakte — das verhindert Verschleiß und ermöglicht präzise analoge Eingaben, z. B. fürs Gasgeben in Rennspielen."),
        ("Bluetooth oder USB-C — was soll ich nutzen?","Für Shooter und schnelle Spiele: USB-C (praktisch kein Input-Lag). Für Couch-Gaming und Cloud Gaming reicht Bluetooth völlig.")]),
"abxylute-s8": dict(
  verdict="Der abxylute S8 ist einer der vielseitigsten Controller im Sortiment: iPhone, iPad, Android und sogar Nintendo Switch 1 & 2 — mit Hall-Sensoren und nur 256 g. Starker Allrounder für 46 €.",
  desc=["Kaum ein Controller deckt so viele Plattformen ab: Der S8 verbindet sich per Bluetooth mit iPhone, iPad, Android-Geräten und der Nintendo Switch (1 und 2). Wer mehrere Geräte besitzt, braucht damit nur noch einen Controller. Die Hall-Sensor-Sticks arbeiten driftfrei, der 1000-mAh-Akku hält lange Sessions durch.",
   "Mit 256 g ist er angenehm leicht, und 4,4 Sterne bei 249 Bewertungen sprechen für sich. Einziger struktureller Nachteil: Als reiner Bluetooth-Controller hat er keinen Telefon-Halter integriert — du brauchst einen Ständer oder eine separate Halterung fürs Handy."],
  pros=["Multiplattform: iPhone, iPad, Android, Switch 1 & 2","Hall-Sensor-Sticks — driftfrei","Nur 256 g, 1000-mAh-Akku","4,4 Sterne bei 249 Bewertungen"],
  cons=["Kein integrierter Handy-Halter (separater Ständer nötig)","Bluetooth-Latenz — USB-C-Clips sind schneller"],
  faqs=[("Funktioniert der S8 wirklich mit der Nintendo Switch 2?","Ja, laut Hersteller und Nutzerberichten unterstützt er Switch 1 und Switch 2 — er wechselt den Modus per Tastenkombination beim Einschalten."),
        ("Wie halte ich mein Handy beim Spielen?","Der S8 ist ein klassisches Gamepad ohne Klemme. Nutze einen Handyständer oder befestige eine Smartphone-Halterung — oder greif zu einem Teleskop-Controller wie dem GameSir X2s, wenn du das Handy im Controller einspannen willst.")]),
"abxylute-m4-snapon": dict(
  verdict="Mit 56 g und MagSafe-Snap-On ist der abxylute M4 der portabelste Controller im Sortiment — 4,5 Sterne bei 361 Bewertungen sind Top-Wert. Für große Hände ist er aber zu klein.",
  desc=["Der M4 verfolgt ein cleveres Konzept: Statt das Handy einzuspannen, schnappt er per MagSafe-Magnet an die Rückseite deines iPhones (oder Android-Handys mit Magnetring) und klappt sich im Handumdrehen zusammen — mit 56 g passt er in jede Hosentasche. Verbunden wird per Bluetooth 5.3.",
   "Die Bewertungen (4,5 Sterne, 361 Rezensionen) gehören zu den besten im ganzen Sortiment. Zwei ehrliche Einschränkungen: Für große Hände sind die kompakten Tasten auf Dauer unbequem, und die Magnethaltung wird in Rezensionen gemischt bewertet — bei wilden Bewegungen kann sich der Controller lösen."],
  pros=["Nur 56 g — passt in jede Hosentasche","MagSafe-Snap-On: kein Einspannen nötig","Bluetooth 5.3 — moderne, stabile Verbindung","4,5 Sterne bei 361 Bewertungen (Top-Wert)"],
  cons=["Für große Hände zu klein","Magnethalt bei intensiven Sessions nicht immer sicher"],
  faqs=[("Brauche ich ein iPhone mit MagSafe?","Am iPhone (12 oder neuer) hält der M4 direkt per MagSafe. Bei Android-Handys brauchst du einen aufklebbaren Magnetring oder eine MagSafe-kompatible Hülle."),
        ("Ist der M4 für lange Gaming-Sessions geeignet?","Eher für unterwegs und Zwischendurch-Sessions. Wer täglich mehrere Stunden spielt, greift besser zu einem ergonomischen Vollformat-Controller wie dem GameSir G8 Galileo.")]),
"8bitdo-ultimate-mobile": dict(
  verdict="Der 8BitDo Ultimate Mobile bringt die bewährte 8BitDo-Qualität ins Mobile Gaming: Hall-Effect-Sticks und -Trigger, Turbo-Funktion und 4,3 Sterne bei 506 Bewertungen für 45 €.",
  desc=["8BitDo hat sich mit Retro- und Switch-Controllern einen exzellenten Ruf erarbeitet — der Ultimate Mobile überträgt das auf Android-Smartphones. Hall-Effect-Joysticks und -Trigger machen Stick-Drift zum Fremdwort, die Turbo-Funktion automatisiert schnelles Tastendrücken in Grind-lastigen Spielen.",
   "Verbunden wird per Bluetooth. Die Verarbeitung liegt spürbar über den No-Name-Alternativen in derselben Preisklasse — dafür steht die Marke. Wichtig zu wissen: Dieses Modell ist auf Android ausgerichtet; iPhone-Nutzer schauen sich besser den abxylute S8 oder Backbone One an."],
  pros=["Hall-Effect-Sticks und -Trigger — driftfrei","Bewährte 8BitDo-Verarbeitungsqualität","Turbo-Funktion für Grind-Games","4,3 Sterne bei 506 Bewertungen"],
  cons=["Primär für Android — kein iPhone-Fokus","Bluetooth-only — kein USB-C-Modus fürs Handy"],
  faqs=[("Funktioniert der Ultimate Mobile mit dem iPhone?","Er ist für Android optimiert. iPhone-Nutzer greifen besser zu einem MFi-zertifizierten oder explizit iOS-kompatiblen Modell wie dem Backbone One oder abxylute S8."),
        ("Was unterscheidet ihn vom 8BitDo Ultimate 2C?","Der Ultimate 2C (ca. 20 €) ist ein kabelgebundener Einsteiger-Controller. Der Ultimate Mobile bietet Bluetooth, Hall-Effect-Trigger und hochwertigere Haptik — dafür kostet er gut das Doppelte.")]),
"viture-8bitdo": dict(
  verdict="Die VITURE-Edition des 8BitDo Ultimate Mobile setzt auf USB-C statt Bluetooth — null Input-Lag, ideal für XR-Brillen und kompetitives Gaming. 79 € sind fair, die Passform hat aber Grenzen.",
  desc=["Diese Kooperation von VITURE (bekannt für XR-Brillen) und 8BitDo unterscheidet sich in einem Kernpunkt vom normalen Ultimate Mobile: Sie ist kabelgebunden per USB-C. Das bedeutet praktisch keinen Input-Lag — und macht den Controller zur ersten Wahl für VITURE-XR-Brillen, Cloud Gaming und schnelle Shooter. Hall-Effect-Sticks sind ebenfalls an Bord.",
   "Zwei Punkte aus den Rezensionen (4,1 Sterne, 234 Bewertungen) solltest du kennen: Bei Handys mit sehr dickem Kamera-Buckel sitzt der Controller nicht immer sauber, und das USB-C-Passthrough (Laden während des Spielens) funktioniert nicht mit jedem Smartphone-Modell."],
  pros=["USB-C-Kabelverbindung — praktisch kein Input-Lag","Hall-Effect-Sticks — driftfrei","Ideal für VITURE-XR-Brillen & Cloud Gaming","8BitDo-Verarbeitungsqualität"],
  cons=["Passform-Probleme bei dicken Kamera-Buckeln","USB-C-Passthrough nicht mit jedem Handy kompatibel"],
  faqs=[("Was ist der Unterschied zur Bluetooth-Version?","Diese VITURE-Edition ist kabelgebunden (USB-C) — dadurch entfällt der Bluetooth-Input-Lag komplett. Dafür muss dein Gerät einen freien USB-C-Port haben."),
        ("Brauche ich eine VITURE-Brille dafür?","Nein. Der Controller funktioniert an jedem Android-Gerät mit USB-C. Die XR-Brillen-Integration ist ein Zusatz-Feature, kein Muss.")]),
"shanwan-metallic": dict(
  verdict="Der ShanWan im Metallic-Braun ist die dritte Farbvariante des bewährten Budget-Teleskop-Controllers — gleiche Technik, gleiche 4,2 Sterne, rund 34 €.",
  desc=["Technisch entspricht das metallic-braune Modell weitgehend den weißen und schwarzen ShanWan-Controllern: Bluetooth-Verbindung, Teleskop-Rahmen zum Einspannen des Handys und eine für die Preisklasse ordentliche Ergonomie. Das Metallic-Finish wirkt hochwertiger, als der Preis vermuten lässt.",
   "Unsere Empfehlung ist hier pragmatisch: Vergleiche die Tagespreise der drei ShanWan-Varianten und nimm die günstigste — funktional nehmen sie sich nichts. Alle drei teilen sich dieselben Stärken (Preis, Key-Mapping) und Schwächen (Bluetooth-Latenz, einfache Haptik)."],
  pros=["Hochwertig wirkendes Metallic-Finish","4,2 Sterne bei 768 Bewertungen","Teleskop-Design mit gutem Halt","Meist unter 35 €"],
  cons=["Bluetooth-Latenz — für schnelle Shooter ungeeignet","Tastenhaptik einfacher als bei Markengeräten"],
  faqs=[("Weiß, schwarz oder metallic — welchen ShanWan nehmen?","Die Technik ist praktisch identisch. Nimm die Farbe, die dir gefällt — oder schlicht die Variante, die gerade am günstigsten ist."),
        ("Für welche Spiele eignet sich der Controller?","RPGs, Adventures, Emulatoren und Cloud Gaming laufen problemlos. Bei kompetitiven Shootern stört die Bluetooth-Latenz — dafür lieber einen USB-C-Controller wählen.")]),
"hellcool-controller": dict(
  verdict="Der HELLCOOL Handheld bietet Hall-Effect-Sticks, RGB und Makro-Tasten schon ab 29 € — auf dem Papier ein Kampfpreis. Die Rezensionen mahnen aber zur Vorsicht bei der Langzeitqualität.",
  desc=["Auf der Feature-Liste liest sich der HELLCOOL wie ein Controller der 60-€-Klasse: Teleskop-Design für Android und iPhone, Hall-Effect-Joysticks, RGB-Beleuchtung sowie Makro- und Turbo-Tasten. Der Preis variiert je nach Tastenlayout (PlayStation-, Switch- oder Xbox-Anordnung) zwischen etwa 29 und 50 €.",
   "Die 4,1 Sterne bei 99 Bewertungen sind ordentlich, aber in den Rezensionen tauchen wiederholt Stick-Drift-Klagen auf — was bei beworbenen Hall-Effect-Sticks stutzig macht. Unser Rat: Als günstiger Zweit- oder Test-Controller in Ordnung; wer langfristige Zuverlässigkeit will, investiert lieber in GameSir oder 8BitDo."],
  pros=["Hall-Effect-Sticks, RGB & Makros ab 29 €","Drei Tastenlayouts zur Wahl (PS/Switch/Xbox)","Teleskop-Design für Android und iPhone"],
  cons=["Wiederholte Stick-Drift-Klagen in Rezensionen","Langzeitqualität unklar — junge Marke"],
  faqs=[("Warum schwankt der Preis so stark?","Der Preis hängt vom gewählten Tastenlayout ab: Die PlayStation-Variante kostet ca. 40 €, Switch ca. 50 €, Xbox ca. 30 €. Technisch sind sie identisch."),
        ("Sind die Hall-Effect-Sticks wirklich driftfrei?","Beworben ja — allerdings berichten einzelne Käufer trotzdem von Drift. Bei etablierten Marken wie GameSir oder 8BitDo ist die Qualitätskontrolle verlässlicher.")]),
"marsgaming-mgp-bt2": dict(
  verdict="Der Mars Gaming MGP-BT2 ist ein Multiplattform-Gamepad für PC, Switch, Android, iOS und sogar PS3/PS4 — mit RGB-Neon und haptischem Feedback für rund 30 €.",
  desc=["Mars Gaming (spanische Budget-Gaming-Marke) packt in den MGP-BT2 eine beachtliche Kompatibilitätsliste: PC, Nintendo Switch und Switch 2, Android, iOS sowie PS3 und PS4. Verbunden wird per Bluetooth 5.0 oder USB-C-Kabel — Letzteres empfehlen wir am PC für minimale Latenz.",
   "Mit 4,0 Sternen bei bisher 25 Bewertungen ist die Datenbasis noch dünn, aber unauffällig. Für 30 € bekommst du ein flexibles Zweit-Gamepad für viele Geräte — erwarte aber keine Hall-Effect-Sticks oder Premium-Haptik."],
  pros=["Sehr breite Kompatibilität (PC/Switch/Android/iOS/PS3/PS4)","Bluetooth 5.0 UND USB-C-Kabelmodus","RGB-Neon-Beleuchtung","Nur ca. 30 €"],
  cons=["Keine Hall-Effect-Sticks","Erst 25 Bewertungen — wenig Langzeiterfahrung"],
  faqs=[("Funktioniert der MGP-BT2 an der Switch 2?","Ja, laut Hersteller werden Switch 1 und Switch 2 unterstützt. Der Plattform-Modus wird beim Einschalten per Tastenkombination gewählt."),
        ("Hat er eine Handy-Halterung?","Er ist ein klassisches Gamepad ohne integrierte Klemme — fürs Smartphone brauchst du einen Ständer oder eine Aufsteck-Halterung.")]),
"marsgaming-mgpx": dict(
  verdict="Der Mars Gaming MGPX ist mit rund 27 € das günstigste Multiplattform-Gamepad im Sortiment — inklusive abnehmbarem Smartphone-Halter und Turbo-Funktion. 4,0 Sterne bei 368 Bewertungen.",
  desc=["Der MGPX deckt PC, Android, iOS, Switch und PS4 ab und legt — anders als viele Budget-Gamepads — einen abnehmbaren Smartphone-Halter bei. Damit wird aus dem klassischen Gamepad ein vollwertiger Handy-Controller, ohne dass du extra Zubehör kaufen musst. Turbo-Funktion und RGB runden das Paket ab.",
   "Mit 368 Bewertungen bei 4,0 Sternen ist er das bewährteste Mars-Gaming-Modell. Die Grenzen sind die üblichen der Preisklasse: Potentiometer-Sticks (kein Hall-Effect) und eine Haptik, die man für 27 € erwarten darf — funktional, nicht luxuriös."],
  pros=["Abnehmbarer Smartphone-Halter inklusive","Multiplattform: PC/Android/iOS/Switch/PS4","Turbo-Funktion","Nur ca. 27 € — 4,0 Sterne bei 368 Bewertungen"],
  cons=["Keine Hall-Effect-Sticks","Einfache Verarbeitungsqualität"],
  faqs=[("Ist der Handy-Halter stabil?","Für normales Spielen ja — das Handy sitzt über dem Gamepad wie bei einer Konsolen-Klemme. Bei sehr großen/schweren Handys mit Hülle wird die Konstruktion kopflastig."),
        ("MGPX oder MGPXPRO — welcher ist besser?","Der MGPXPRO hat Hall-Effect-Sticks, aber bisher schwache Bewertungen (3,3 Sterne). Der normale MGPX ist mit 368 Bewertungen bei 4,0 Sternen aktuell die sicherere Wahl.")]),
"marsgaming-mgpxpro": dict(
  verdict="Der MGPXPRO bietet Hall-Effect-Sticks und -Trigger für nur 36 € — klingt stark, aber 3,3 Sterne bei den ersten Bewertungen sind ein Warnsignal. Aktuell keine Kaufempfehlung.",
  desc=["Auf dem Papier ist der MGPXPRO ein Schnäppchen: Hall-Effect-Joysticks und -Trigger (normalerweise ein Feature der 50-€-Klasse und darüber), 2-in-1-Design mit Handy-Halterung und breite Plattform-Unterstützung von PS4 über Switch 2 bis Android und iOS.",
   "Wir bleiben hier bewusst ehrlich: Mit 3,3 Sternen bei den ersten 7 Bewertungen ist der Start schwach ausgefallen. Die Datenbasis ist klein, aber solange sich das Bild nicht bessert, empfehlen wir Alternativen — den bewährten MGPX (4,0 Sterne) oder für 10 € mehr den EasySMX M15 mit derselben Hall-Effect-Technik und 721 Bewertungen."],
  pros=["Hall-Effect-Sticks und -Trigger für nur 36 €","2-in-1: Gamepad + Handy-Halterung","Breite Plattform-Unterstützung inkl. Switch 2"],
  cons=["Nur 3,3 Sterne bei ersten Bewertungen — Warnsignal","Kaum Langzeiterfahrungen verfügbar"],
  faqs=[("Warum ratet ihr trotz Hall-Effect ab?","Technik auf dem Datenblatt nützt nichts, wenn die Ausführung nicht stimmt. 3,3 Sterne — auch bei kleiner Datenbasis — sind unterdurchschnittlich. Wir beobachten das Modell und aktualisieren die Einschätzung."),
        ("Welche Alternative empfehlt ihr?","Der EasySMX M15 (ca. 50 €) bietet dieselbe Hall-Effect-Ausstattung mit 4,2 Sternen bei über 700 Bewertungen — das Geld ist dort besser angelegt.")]),
"wllhyf-sleeves": dict(
  verdict="Die WLLHYF Anti-Schweiß-Sleeves aus Nylon mit Silberfaser sind ein solides 10er-Set für 7 € — atmungsaktiv, touchscreen-tauglich, 4,3 Sterne.",
  desc=["Finger Sleeves lösen ein simples Problem: Schwitzige Daumen rutschen und ziehen Schlieren übers Display. Die WLLHYF-Hülsen kombinieren Nylon und Elasthan mit leitfähiger Silberfaser — dadurch bleiben Wischgesten und Taps präzise, während der Stoff Schweiß aufnimmt.",
   "Im 10er-Set kosten sie rund 7 € und liegen mit 4,3 Sternen (60 Bewertungen) im grünen Bereich. Preisbewusste Vielspieler vergleichen sie am besten direkt mit dem RISOKA-Set — dem Bestseller der Kategorie mit fast 2.800 Bewertungen für ein paar Euro mehr."],
  pros=["Silberfaser — zuverlässig leitfähig","Atmungsaktives Nylon-Elasthan-Gewebe","10 Stück für ca. 7 €","4,3 Sterne bei 60 Bewertungen"],
  cons=["Deutlich weniger Langzeiterfahrungen als beim RISOKA-Set","Größe nicht verstellbar"],
  faqs=[("Wofür braucht man Finger Sleeves überhaupt?","Vor allem für Touchscreen-Shooter wie PUBG Mobile oder CoD Mobile: Sie verhindern schwitzige, rutschende Daumen und sorgen für gleichmäßiges Gleiten auf dem Display."),
        ("Wie oft kann man die Sleeves waschen?","Handwäsche mit mildem Waschmittel ist unproblematisch. Mit 10 Stück im Set kannst du zudem rotieren, während einzelne trocknen.")]),
"ouligay-sleeves": dict(
  verdict="30 Carbonfaser-Sleeves für 7 € — der Ouligay-Massenpack ist der Preis-Leistungs-Sieger für Verbraucher, die Sleeves als Verschleißartikel sehen. Achtung: Die Größen fallen klein aus.",
  desc=["Ouligay setzt auf Masse: 30 Fingerhülsen aus leitfähiger Carbonfaser für rund 7 € — das sind etwa 23 Cent pro Stück. Wer Sleeves täglich nutzt und regelmäßig durchwechselt, fährt mit diesem Pack am günstigsten. Touchscreen-Tauglichkeit und Passform sind für den Preis ordentlich (4,1 Sterne bei 257 Bewertungen).",
   "Der wichtigste Kritikpunkt aus den Rezensionen: Die Größen fallen klein aus. Bei kräftigen Daumen sitzen die Hülsen unangenehm stramm — dann sind die dehnbareren RISOKA- oder WLLHYF-Sets die bessere Wahl."],
  pros=["30 Stück für ca. 7 € — bester Stückpreis","Carbonfaser — gute Leitfähigkeit","4,1 Sterne bei 257 Bewertungen"],
  cons=["Größen fallen klein aus — eng bei kräftigen Daumen","Einzelne Hülsen leiern schneller aus als Marken-Sets"],
  faqs=[("Carbonfaser oder Silberfaser — was ist besser?","Beide leiten zuverlässig. Silberfaser (z. B. RISOKA) gilt als etwas langlebiger und hygienischer, Carbonfaser ist günstiger in der Masse."),
        ("Für wen lohnt sich der 30er-Pack?","Für Vielspieler, die Sleeves als Verbrauchsmaterial betrachten und häufig wechseln — oder für Familien/Teams, die sich ein Set teilen.")]),
"risoka-finger-sleeves": dict(
  verdict="Der Amazon-Bestseller unter den Finger Sleeves: 4,4 Sterne bei fast 2.800 Bewertungen sprechen eine klare Sprache. Das RISOKA 10er-Set ist unsere Standard-Empfehlung der Kategorie.",
  desc=["Kein anderes Sleeve-Set im deutschen Markt ist so breit validiert: 2.759 Bewertungen bei 4,4 Sternen machen die RISOKA-Hülsen zum unangefochtenen Bestseller. Die Silberfaser-Webung leitet zuverlässig auf allen Touchscreens — Handy wie Tablet — und das atmungsaktive Gewebe hält auch lange PUBG- oder CoD-Sessions trocken.",
   "Mit rund 13 € für 10 Stück sind sie teurer als die Massenpacks von Ouligay oder RXKFIGX — der Aufpreis kauft aber spürbar konsistentere Qualität und Langlebigkeit. Wenn du nur ein Sleeve-Set ausprobieren willst: dieses."],
  pros=["4,4 Sterne bei 2.759 Bewertungen — Bestseller","Silberfaser: präzise Leitfähigkeit auf jedem Display","Atmungsaktiv — trockene Daumen auch bei langen Sessions","Passt auf Handy und Tablet"],
  cons=["Höherer Stückpreis als die Massenpacks","Bei sehr schmalen Fingern anfangs locker"],
  faqs=[("Warum sind die RISOKA-Sleeves die Empfehlung?","Die Kombination aus Silberfaser-Qualität und der mit Abstand größten Bewertungsbasis (fast 2.800 Rezensionen) macht sie zur sichersten Wahl — hier kaufst du kein Überraschungsei."),
        ("Merkt man den Unterschied zu billigeren Sets wirklich?","Ja, vor allem bei der Haltbarkeit: Günstige Polyester-Sleeves leiern schneller aus oder verlieren Leitfähigkeit. Die RISOKA halten bei täglicher Nutzung mehrere Monate.")]),
"rxkfigx-sleeves": dict(
  verdict="40 Sleeves für 7 € klingt verlockend — aber 3,5 Sterne und wiederholte „löst sich auf“-Klagen machen den RXKFIGX-Pack zur Notlösung. Wir empfehlen die Alternativen.",
  desc=["Der RXKFIGX-Pack ist das größte Set im Sortiment: 40 Polyesterfaser-Hülsen für rund 7 € — nominell der niedrigste Stückpreis überhaupt. Die Touchscreen-Tauglichkeit ist grundsätzlich gegeben.",
   "Wir bleiben aber bei unserer ehrlichen Linie: 3,5 Sterne bei 36 Bewertungen sind das schwächste Ergebnis der Kategorie, und mehrere Rezensenten berichten, dass sich die Hülsen nach kurzer Zeit auflösen oder die Leitfähigkeit verlieren. Polyester ist Silber- und Carbonfaser hier schlicht unterlegen. Wer günstig in Masse kaufen will, greift besser zum Ouligay-30er-Pack (4,1 Sterne)."],
  pros=["Größtes Set: 40 Stück für ca. 7 €","Niedrigster Stückpreis der Kategorie"],
  cons=["Nur 3,5 Sterne — schwächster Wert der Kategorie","„Löst sich auf“-Klagen in Rezensionen","Polyester leitet schlechter als Silber-/Carbonfaser"],
  faqs=[("Warum listet ihr das Produkt trotzdem?","Transparenz: Der Pack taucht in Amazon-Suchen prominent auf. Wir zeigen dir die ehrliche Einordnung, damit du vergleichen kannst — unsere Empfehlung bleiben RISOKA (Qualität) und Ouligay (Preis)."),
        ("Sind alle Polyester-Sleeves schlecht?","Nicht grundsätzlich — aber Silber- und Carbonfaser sind leitfähiger und haltbarer. Bei nur 1–3 € Preisunterschied lohnt sich das Sparen am Material nicht.")]),
"magnet-peltier-cooler": dict(
  verdict="Der günstigste Weg zu aktiver Handy-Kühlung: Peltier-Element plus Lüfter, wahlweise per Clip oder Magnet montiert, für rund 17 €. Die Kühlleistung ist okay, aber kein Spitzenwert.",
  desc=["Beim Zocken drosseln Smartphones ihre Leistung, sobald sie zu heiß werden (Thermal Throttling) — genau dagegen arbeitet dieser 2-in-1-Kühler: Ein Peltier-Element erzeugt aktiv Kälte, ein Lüfter mit drei Stufen führt die Wärme ab. Montiert wird wahlweise per Klemm-Clip oder Magnet (MagSafe-kompatibel), RGB-Beleuchtung inklusive.",
   "Mit 17 € ist er der klare Budget-Einstieg in die aktive Kühlung. Er hängt aber dauerhaft am USB-Kabel (kein Akku), und die Kühlleistung reicht nicht an die 20-Watt-Klasse des Black Shark FunCooler heran. Für gelegentliche Genshin- oder PUBG-Sessions genügt er."],
  pros=["Günstigster Peltier-Kühler (ca. 17 €)","Flexibel: Clip- ODER Magnet-Montage","3 Lüfterstufen + RGB"],
  cons=["Kühlleistung unter der 20W-Konkurrenz","Kein Akku — läuft nur am USB-Kabel"],
  faqs=[("Bringt ein Handy-Kühler wirklich etwas?","Ja, messbar — bei langen Sessions in anspruchsvollen Spielen verhindert er Thermal Throttling, also das automatische Drosseln der Leistung. Bei kurzen Casual-Sessions ist der Effekt gering."),
        ("Clip oder Magnet — was ist besser?","Magnet (MagSafe) ist bequemer und positioniert den Kühler wiederholbar an derselben Stelle. Der Clip funktioniert dafür an jedem Handy, auch ohne Magnetring.")]),
"black-shark-funcooler": dict(
  verdict="Der Black Shark FunCooler 6 ist der stärkste Kühler im Sortiment: 20-Watt-Peltier, MagSafe und App-Steuerung. Er braucht aber zwingend ein kräftiges Netzteil.",
  desc=["Black Shark (die Gaming-Marke aus dem Xiaomi-Umfeld) baut seit Jahren die Referenz-Kühler fürs Mobile Gaming. Der FunCooler 6 kühlt mit einem 20-Watt-Peltier-Element und ICECOLD-2.0-Technik spürbar stärker als die Budget-Konkurrenz — bei langen Ranked-Sessions in Genshin Impact oder PUBG Mobile bleibt das Handy auch nach Stunden leistungsstabil.",
   "Montiert wird per MagSafe oder Clip, gesteuert wahlweise per App. Der wichtigste Praxis-Hinweis: Das Peltier-Element zieht richtig Strom — du brauchst ein USB-C-Netzteil mit mindestens 20 Watt. Am Laptop-USB-Port oder schwachen Ladegerät bleibt die Kühlleistung deutlich unter ihrem Potenzial."],
  pros=["Stärkste Kühlleistung im Sortiment (20W Peltier)","MagSafe + Clip-Montage","App-Steuerung mit Temperaturanzeige","ICECOLD 2.0 — schnelles Herunterkühlen"],
  cons=["Benötigt zwingend ≥20W-USB-C-Netzteil","Mit ca. 40 € kein Impulskauf"],
  faqs=[("Warum braucht der FunCooler ein 20W-Netzteil?","Das Peltier-Element wandelt Strom direkt in Kälte um — je mehr Leistung anliegt, desto stärker kühlt es. An schwachen Ports läuft nur der Lüfter auf Sparflamme."),
        ("Lohnt sich der Aufpreis gegenüber dem 17-€-Kühler?","Wenn du regelmäßig lange, anspruchsvolle Sessions spielst: ja, deutlich. Für Gelegenheitsspieler reicht der günstige Peltier-Clip-Kühler.")]),
"razer-phone-cooler": dict(
  verdict="Razers Phone Cooler Chroma kombiniert Peltier-Kühlung mit der bekannten Chroma-RGB-Beleuchtung — starke Kühlleistung im Markendesign, aber hörbar laut und mit 46 € der teuerste Kühler.",
  desc=["Der Phone Cooler Chroma ist Razers Antwort auf die Handy-Kühler-Klasse: Ein Peltier-Element mit Lüfter, eingefasst in das typische Razer-Design mit 12 Chroma-RGB-LEDs, die sich per App synchronisieren lassen. Die Kühlleistung ist stark und hält Flaggschiff-Handys auch in langen Sessions unter der Drossel-Grenze.",
   "Zwei ehrliche Punkte: Der Lüfter ist unter Volllast deutlich hörbar — mit Lautsprecher-Sound am Handy störend, mit Kopfhörern egal. Und wie alle Peltier-Kühler läuft er nur am USB-C-Netzteil, nicht per Akku. Wer das Razer-Ökosystem mag, zahlt hier den Markenaufschlag von rund 10 € gegenüber dem Black Shark."],
  pros=["Starke Peltier-Kühlleistung","Chroma-RGB mit App-Anbindung","MagSafe-Montage (iPhone) + Clip-Option","Razer-Verarbeitungsqualität"],
  cons=["Unter Volllast deutlich hörbar","Teuerster Kühler im Sortiment (ca. 46 €)","Kein Akku — Netzteilbetrieb"],
  faqs=[("Razer oder Black Shark — welcher Kühler?","Der Black Shark FunCooler 6 kühlt mindestens gleichwertig und kostet weniger. Der Razer punktet mit Chroma-RGB und der Integration ins Razer-Ökosystem — reine Geschmacks- und Markenfrage."),
        ("Funktioniert der Kühler am Android-Handy?","Ja — per Klemm-Mechanik an praktisch jedem Smartphone. Die MagSafe-Magnetmontage ist iPhones (12+) bzw. Handys mit Magnetring vorbehalten.")]),
"risoka-trigger": dict(
  verdict="Die RISOKA Dual-Trigger bieten 4 Aktionen über 2 anpassbare Tasten pro Seite mit mechanischem Feedback — ein durchdachtes Trigger-Paar für rund 20 €.",
  desc=["Anders als simple L1R1-Klemmen bieten die RISOKA-Trigger zwei belegbare Tasten pro Seite — insgesamt vier Aktionen, die du in Shootern wie PUBG Mobile oder CoD Mobile auf Schießen, Zielen, Springen und Nachladen legen kannst. Das mechanische Feedback gibt einen klar spürbaren Druckpunkt.",
   "Die Klemmen passen auf Smartphones bis 11 mm Dicke — mit dünner Hülle klappt das meist noch, dicke Outdoor-Cases musst du abnehmen. Wie alle mechanischen Trigger arbeiten sie rein physisch aufs Display: kein Bluetooth, keine App, kein Bann-Risiko in PUBG & CoD."],
  pros=["4 Aktionen (2 Tasten pro Seite) statt nur 2","Mechanischer Druckpunkt — klares Feedback","Kein Bluetooth/App — kein Bann-Risiko","Passt auf Smartphones bis 11 mm"],
  cons=["Dicke Hüllen müssen ab","Positionierung braucht anfangs Feintuning"],
  faqs=[("Sind Trigger in PUBG Mobile erlaubt?","Ja — mechanische Trigger drücken physisch aufs Display und sind von den Nutzungsbedingungen gedeckt. Verboten sind Software-Hilfen, keine Hardware-Aufsätze."),
        ("Was bringt die zweite Taste pro Seite?","Du kannst z. B. links Zielen + Granate und rechts Schießen + Springen belegen — 6-Finger-Steuerung ohne Verrenkungen.")]),
"ozkak-6finger": dict(
  verdict="Der Ozkak 4-Auslöser-Grip macht 6-Finger-Gaming möglich: 4 kapazitive Trigger, Gummipuffer zum Displayschutz — solide Basis für 17 €.",
  desc=["Dieser Grip klemmt ans Smartphone und ergänzt vier kapazitive Auslöser (L1/R1/L2/R2) — deine Zeigefinger übernehmen Schießen und Zielen, die Daumen bleiben frei fürs Bewegen und Umschauen: klassische 6-Finger-Steuerung, wie sie ambitionierte PUBG- und CoD-Mobile-Spieler nutzen.",
   "Kapazitive Auslöser leiten die Berührung elektrisch weiter statt mechanisch zu drücken — das arbeitet lautlos und ohne Kraftaufwand. Die Gummipuffer schützen dabei Display und Rahmen. Kompatibel mit iOS- und Android-Geräten von 3 bis 12 mm Dicke, also auch mit vielen Hüllen."],
  pros=["4 Auslöser für echte 6-Finger-Steuerung","Kapazitiv — lautlos, kein Kraftaufwand","Gummipuffer schonen Display und Rahmen","Große Kompatibilität (3–12 mm Gerätedicke)"],
  cons=["Kapazitive Auslöser: weniger spürbarer Druckpunkt als mechanische","Eingewöhnungszeit für 6-Finger-Layout"],
  faqs=[("Kapazitiv oder mechanisch — was ist besser?","Geschmackssache: Kapazitive Trigger (wie hier) reagieren auf Berührung — schnell und lautlos. Mechanische geben einen fühlbaren Klick. Einsteiger kommen mit mechanischen oft schneller zurecht."),
        ("Funktioniert der Grip mit Hülle?","Bis 12 mm Gesamtdicke ja — das schließt die meisten normalen Hüllen ein. Nur dicke Outdoor-Cases sind zu viel.")]),
"ozkak-trigger-set": dict(
  verdict="Der Ozkak AK77 ist Grip, Kühler und Powerbank in einem: 4 Trigger, eingebauter Lüfter und 4000-mAh-Akku. Mit 4,2 Sternen bei 450 Bewertungen das Multitool unter den Grips — 27 €.",
  desc=["Der AK77 verfolgt einen anderen Ansatz als reine Trigger-Klemmen: Er ist ein vollwertiger Controller-Grip, der das Handy wie ein Gamepad in die Hände legt — und dabei gleich drei Probleme löst. Vier Trigger (L1/R1/L2/R2) ermöglichen 6-Finger-Steuerung, der eingebaute Lüfter kühlt die Handy-Rückseite, und der 4000-mAh-Akku lädt das Gerät während des Spielens.",
   "4,2 Sterne bei 450 Bewertungen bestätigen das Konzept. Ein Hinweis aus den Rezensionen: Ohne Hülle kann die Klemmmechanik Kratzer am Handy-Rahmen hinterlassen — eine dünne Hülle oder die beigelegten Polster schaffen Abhilfe."],
  pros=["3-in-1: Trigger + Lüfter-Kühlung + 4000-mAh-Powerbank","4 Trigger für 6-Finger-Steuerung","Ergonomischer Gamepad-Griff","4,2 Sterne bei 450 Bewertungen"],
  cons=["Kratzer-Gefahr ohne Hülle (Klemmmechanik)","Mit Lüfter + Akku spürbar schwerer als reine Trigger"],
  faqs=[("Wie lange hält der eingebaute Akku?","Die 4000 mAh reichen je nach Lüfterstufe für mehrere Stunden Betrieb — und laden das Handy nebenbei. Für einen ganzen Gaming-Tag solltest du den Grip zwischendurch nachladen."),
        ("Ersetzt der Lüfter einen richtigen Handy-Kühler?","Er hilft spürbar, kommt aber nicht an Peltier-Kühler wie den Black Shark FunCooler heran. Für die Kombination aus Grip + Grundkühlung ist er trotzdem einzigartig praktisch.")]),
"ozkak-mini-portable": dict(
  verdict="Für 10 € der günstigste Einstieg ins Trigger-Gaming: Zwei Aufsteck-Auslöser (L1/R1) mit physischen Kontakten — simpel, klein, funktioniert.",
  desc=["Wer Trigger einfach mal ausprobieren will, ohne 20–30 € auszugeben, startet hier: Zwei einzelne Aufsteck-Auslöser klemmen an die obere Handykante und geben dir Schießen und Zielen auf die Zeigefinger. Die physischen Kontakte drücken direkt aufs Display — kein Bluetooth, keine App, kein Akku.",
   "Die Klemmen passen auf Geräte von 5 bis 9 mm Dicke — das ist enger als bei den größeren Grips, dünne Hüllen können also schon zu viel sein. Dafür verschwinden die Mini-Trigger in jeder Hosentasche und sind in Sekunden montiert."],
  pros=["Nur ca. 10 € — günstigster Trigger-Einstieg","In Sekunden montiert, extrem kompakt","Kein Bluetooth/Akku — funktioniert immer"],
  cons=["Nur 2 Auslöser (kein L2/R2)","Enge Klemmweite (5–9 mm) — meist ohne Hülle"],
  faqs=[("Reichen 2 Trigger oder brauche ich 4?","Für den Einstieg reichen 2 (Schießen + Zielen) völlig. Wer später auf 6-Finger-Profi-Layouts umsteigt, greift zu 4-Auslöser-Grips wie dem Ozkak L1R1-Grip."),
        ("Muss ich die Hülle abnehmen?","Bei 5–9 mm Klemmweite: sehr wahrscheinlich ja. Die meisten Handys sind mit Hülle dicker als 9 mm.")]),
"ozkak-trigger-l1r1": dict(
  verdict="Der Ozkak L1R1-Grip bietet 4 Auslöser mit vergoldeten Kontakten und großer Klemmweite (5–13 mm) — mit 669 Bewertungen der meistgekaufte Trigger-Grip im Sortiment. 18 €.",
  desc=["Dieser Clip-On-Grip rüstet vier Auslöser (L1/R1/L2/R2) für die 6-Finger-Steuerung nach. Die Kontakte sind vergoldet — das verhindert Korrosion und hält die Auslöse-Präzision über die Zeit stabil. Gearbeitet wird rein physisch aufs Display: kein Bluetooth, kein Akku, kein Bann-Risiko in PUBG oder CoD Mobile.",
   "Mit einer Klemmweite von 5 bis 13 mm schluckt er auch Handys mit normaler Hülle — das können die günstigeren Mini-Trigger nicht. 3,9 Sterne bei 669 Bewertungen zeigen: solide Massenware mit bekannten Schwächen (Positionierung braucht Übung), aber ohne Ausfall-Drama."],
  pros=["4 Auslöser mit vergoldeten Kontakten","Große Klemmweite 5–13 mm — hüllentauglich","Kein Bluetooth/Akku — kein Bann-Risiko","669 Bewertungen — meistgekaufter Trigger-Grip"],
  cons=["3,9 Sterne — Positionierung braucht Eingewöhnung","Rein mechanisch: hörbares Klicken"],
  faqs=[("Was bringen vergoldete Kontakte?","Gold korrodiert nicht — die Kontaktpunkte bleiben dauerhaft leitfähig und präzise. Bei billigen unbeschichteten Kontakten lässt die Auslösung mit der Zeit nach."),
        ("Warum ist die Bewertung ‚nur' 3,9?","Der häufigste Kritikpunkt ist die anfängliche Positionierung der Auslöser über den Touch-Zonen — das braucht ein paar Versuche. Wer sich die 10 Minuten nimmt, ist danach zufrieden.")]),
"toaluea-trigger-joystick": dict(
  verdict="Der günstigste 4-Auslöser-Grip im Sortiment: vergoldete Metallkontakte und Schutzpolster für nur 9 € — ein fairer Deal für Einsteiger ins 6-Finger-Gaming.",
  desc=["Toaluea unterbietet mit diesem Grip die Ozkak-Konkurrenz preislich deutlich: Vier Auslöser (L1/R1/L2/R2) mit vergoldeten Metallkontakten für rund 9 € — die Ausstattung, für die andere 17–18 € verlangen. Die Clip-Konstruktion bringt Polster mit, die das Display beim Anklemmen schützen.",
   "Bei dem Preis gibt es naturgemäß Abstriche in der Verarbeitungskonstanz — die Klemmen wirken einfacher als beim Ozkak-Pendant. Als risikoarmer Test, ob 6-Finger-Steuerung überhaupt dein Ding ist, ist er aber die vernünftigste Option: 9 € tun nicht weh."],
  pros=["Nur ca. 9 € — günstigster 4-Auslöser-Grip","Vergoldete Metallkontakte","Schutzpolster gegen Display-Kratzer","Passt auf Smartphones 5–13 mm"],
  cons=["Einfachere Verarbeitung als Ozkak & Co.","Wenig Langzeit-Erfahrungsberichte"],
  faqs=[("Toaluea oder Ozkak L1R1 — welchen Grip nehmen?","Der Ozkak (18 €) hat mit 669 Bewertungen die deutlich größere Erfahrungsbasis. Der Toaluea ist die Budget-Wette — halber Preis, gleiches Konzept, weniger Absicherung."),
        ("Funktionieren die Trigger in jedem Spiel?","In jedem Spiel mit Touch-Steuerung, bei dem Schießen/Zielen als Bildschirm-Buttons liegen — also PUBG Mobile, CoD Mobile, Free Fire & Co. Spiele mit reiner Controller-Unterstützung brauchen keine Trigger.")]),
"ozkak-trigger-gamepad": dict(
  verdict="Der einzige Trigger-Grip speziell für Tablets: 4 Auslöser für iPads und Tablets von 7–13 Zoll plus elektronischer Schnellfeuer-Modus mit 5 Stufen. 33 €.",
  desc=["Trigger-Grips gibt es viele — aber fast alle sind für Smartphones gebaut. Dieser Ozkak-Grip ist die Ausnahme: Er klemmt an Tablets und iPads von 7 bis 13 Zoll und bringt vier Auslöser für die 6-Finger-Steuerung mit. Wer PUBG Mobile oder CoD Mobile auf dem großen Display spielt, findet kaum Alternativen.",
   "Besonderheit ist der elektronische Schnellfeuer-Modus mit fünf einstellbaren Stufen — er wiederholt Tastendrücke automatisch. Wichtig: In kompetitiven Shootern bewegt sich automatisiertes Schnellfeuer in einer Grauzone der Nutzungsbedingungen; nutze es verantwortungsvoll bzw. in Single-Player-Titeln. Das Tablet sollte unter 10 mm dick sein."],
  pros=["Einzigartig: Trigger-Lösung für Tablets 7–13\"","4 Auslöser für 6-Finger-Steuerung","Schnellfeuer mit 5 einstellbaren Stufen"],
  cons=["Schnellfeuer in kompetitiven Shootern Grauzone","Tablet-Dicke auf <10 mm begrenzt (Hülle meist ab)"],
  faqs=[("Funktioniert der Grip am iPad Pro 12.9?","Ja — die Klemmweite reicht bis 13 Zoll Displaydiagonale. Dicke Hüllen musst du abnehmen (max. ~10 mm Gerätedicke)."),
        ("Ist der Schnellfeuer-Modus erlaubt?","Mechanische Trigger sind unkritisch — elektronisch automatisiertes Schnellfeuer kann je nach Spiel gegen die Fair-Play-Regeln verstoßen. In PUBG/CoD Mobile empfehlen wir, den Modus deaktiviert zu lassen.")]),
"razer-kishi-ultra": dict(
  verdict="Der Kishi Ultra kostet 119 € und ist der einzige Controller bei uns, der ausdrücklich auch an ein iPad mini passt. Der Haken: Nur die Trigger arbeiten mit Hall-Sensorik, die Analogsticks nicht.",
  desc=["Der Razer Kishi Ultra ist ein USB-C-Controller, der laut Hersteller nicht nur an iPhone und Android-Smartphones passt, sondern auch an ein iPad mini beziehungsweise Tablets bis 8 Zoll. Das ist im Sortiment die Ausnahme: Die meisten Teleskop-Modelle enden bei der Smartphone-Größe. Dazu kommen ein mecha-taktiles 8-Wege-Steuerkreuz, programmierbare Tasten, eine 3,5-mm-Klinkenbuchse und Passthrough-Laden, damit das Handy während der Session weiterlädt.",
   "Beim Blick auf die Sticks lohnt Genauigkeit: Razer verbaut Hall-Effekt-Sensorik nur bei den Triggern, die Analogsticks sind TPSiV-Sticks. Der Drift-Schutz, für den Hall-Technik bekannt ist, gilt hier also nicht für die Sticks. Zum Vergleich aus unserem eigenen Sortiment: Der GameSir G8 Plus kostet 76 € und hat Hall-Sensorik bei Sticks und Triggern.",
   "Für wen lohnt er sich? Wenn du auf einem iPad mini oder einem kleinen Tablet mit Controller spielen willst und Wert auf Klinkenbuchse und Passthrough legst, ist er im Sortiment die naheliegende Wahl. Geht es dir nur um einen Controller fürs Handy, bekommst du mit dem GameSir G8 Plus (76 €) oder dem Razer Kishi V3 (94 €) mehr Technik pro Euro."],
  pros=["Passt laut Hersteller auch an iPad mini und Tablets bis 8 Zoll","3,5-mm-Klinke und Passthrough-Laden an Bord","Mecha-taktiles Steuerkreuz und programmierbare Tasten","Razer Nexus App ohne Abo, dazu PC Remote Play"],
  cons=["Hall-Sensorik nur bei den Triggern, die Analogsticks sind TPSiV","119 € trotz 4,0 Sternen bei 110 Bewertungen, der günstigere Kishi V3 (94 €) ist besser bewertet","Die Produktseite nennt nur USB-C, ein Bluetooth-Betrieb ist nicht belegt","Chroma-RGB ist Geschmackssache und für das Spielgefühl ohne Nutzen"],
  faqs=[("Hat der Razer Kishi Ultra Hall-Effect-Sticks?","Nein. Razer nennt Hall-Effekt ausdrücklich nur für die Trigger, die Analogsticks sind TPSiV-Sticks. Wenn du driftfreie Sticks willst, sind der GameSir G8 Plus (76 €, Hall) oder der Razer Kishi V3 (94 €, TMR) die passenderen Modelle."),
        ("Passt der Kishi Ultra an ein iPad mini?","Ja, Razer gibt iPad mini und Tablets bis 8 Zoll ausdrücklich an. Größere Tablets passen nicht: Ab der normalen iPad-Größe brauchst du ein Bluetooth-Gamepad plus Ständer."),
        ("Lohnt der Aufpreis gegenüber dem Kishi V3?","Nur wegen des Tablet-Formats, der Klinkenbuchse und der Haptik. Rein technisch bekommst du beim 25 € günstigeren Kishi V3 die moderneren TMR-Sticks.")]),

"scuf-nomad": dict(
  verdict="Der Scuf Nomad ist ein reiner iPhone-Controller: 73 €, Bluetooth 5.0, Hall-Effekt-Sticks mit Wechselkappen und zwei belegbare Rücktasten. Android-Betrieb gibt Scuf nicht an, und 4,0 Sterne bei 157 Bewertungen sind solide, aber kein Spitzenwert.",
  desc=["Der Scuf Nomad verbindet sich per Bluetooth 5.0 mit dem iPhone und bringt zwei Ausstattungsmerkmale mit, die man in dieser Preisklasse selten zusammen findet: Analogsticks in voller Größe mit Hall-Effekt-Sensorik und drei wechselbaren Kappen (lang, gewölbt, konkav) sowie zwei frei belegbare Paddles auf der Rückseite. Über die kostenlose SCUF-App lassen sich Reaktionskurven von Sticks und Triggern anpassen und als Profile speichern, ein Abo verlangt Scuf dafür nicht.",
   "Zwei Punkte solltest du vor dem Kauf kennen. Erstens ist er ein iPhone-Gerät: Amazon führt ihn im Plattform-Feld als iOS, und Scuf nennt ihn selbst im Produkttitel iPhone-Controller. Für Android ist er damit kein Kandidat. Zweitens kostet Bluetooth Tempo. Gegenüber den USB-C-Modellen im Sortiment ist die Verzögerung spürbar, und beim Cloud Gaming addiert sie sich zur Streaming-Latenz. Für Rollenspiele, Emulatoren und entspannte Sessions fällt das kaum auf, in kompetitiven Shootern schon.",
   "Der eigene Akku (laut Scuf 16 Stunden) hat zwei Seiten: Der Controller zieht keinen Strom aus dem Handy, muss aber selbst geladen werden. Und der Preis-Nachbar drängt sich auf: Für 3 € mehr bietet der GameSir G8 Plus (76 €) Hall-Sensorik bei Sticks und Triggern, Bluetooth und Kabel sowie Android, Tablet und Switch. Der Nomad lohnt sich, wenn du am iPhone kabellos spielst und die Rücktasten wirklich nutzt."],
  pros=["Hall-Effekt-Sticks in voller Größe mit drei wechselbaren Kappen","Zwei frei belegbare Paddles auf der Rückseite","Eigener Akku, laut Scuf 16 Stunden, ohne Strom aus dem Handy zu ziehen","Kostenlose SCUF-App für Reaktionskurven und Profile, kein Abo"],
  cons=["Reiner iPhone-Controller, Android-Betrieb gibt Scuf nicht an","Bluetooth statt Kabel: spürbare Latenz, kein Controller für kompetitive Shooter","Für 3 € mehr bietet der GameSir G8 Plus (76 €) Hall-Sticks plus Hall-Trigger, Kabel und Android","4,0 Sterne bei 157 Bewertungen liegen unter den meisten iPhone-Alternativen im Sortiment"],
  faqs=[("Funktioniert der Scuf Nomad mit Android?","Scuf gibt das nicht an: Amazon führt ihn im Plattform-Feld als iOS-Gerät, im Produkttitel heißt er iPhone-Controller. Wir versprechen dir nichts, was der Hersteller nicht belegt. Für Android nimm den GameSir G8 Plus (76 €) oder den GameSir X5 Lite (38 €, USB-C)."),
        ("Taugt der Nomad für Cloud Gaming?","Für PS Remote Play, Xbox Game Pass oder Steam Link ja, mit einer Einschränkung: Zur Streaming-Verzögerung kommt die Bluetooth-Latenz dazu. In gemütlichen Spielen merkst du das kaum, in Shootern wird es unangenehm."),
        ("Hat der Scuf Nomad wirklich Hall-Effect-Sticks?","Ja, Scuf gibt Hall-Effekt-Thumbsticks an. Das schützt vor Stick-Drift, ist aber kein Alleinstellungsmerkmal mehr: Hall-Sticks gibt es in unserem Sortiment schon ab 20 € (8BitDo Ultimate 2C). Besonders sind hier die volle Stick-Größe und die drei Wechselkappen.")]),
}
